package team

const (
	LeftTop            = "(l t)"
	PenaltyLeftTop     = "(p l t)"
	PenaltyLeftCenter  = "(p l c)"
	PenaltyLeftBottom  = "(p l b)"
	LeftBottom         = "(l b)"
	GoalLeftTop        = "(g l t)"
	GoalLeftBottom     = "(g l b)"
	CenterTop          = "(c t)"
	Center             = "(c)"
	CenterBottom       = "(c b)"
	RightTop           = "(r t)"
	PenaltyRightTop    = "(p r t)"
	PenaltyRightCenter = "(p r c)"
	PenaltyRightBottom = "(p r b)"
	RightBottom        = "(r b)"
	GoalRightTop       = "(g r t)"
	GoalRightBottom    = "(g r b)"

	TopLeft50  = "(t l 50)"
	TopLeft40  = "(t l 40)"
	TopLeft30  = "(t l 30)"
	TopLeft20  = "(t l 20)"
	TopLeft10  = "(t l 10)"
	Top0       = "(t 0)"
	TopRight10 = "(t r 10)"
	TopRight20 = "(t r 20)"
	TopRight30 = "(t r 30)"
	TopRight40 = "(t r 40)"
	TopRight50 = "(t r 50)"

	BottomLeft50  = "(b l 50)"
	BottomLeft40  = "(b l 40)"
	BottomLeft30  = "(b l 30)"
	BottomLeft20  = "(b l 20)"
	BottomLeft10  = "(b l 10)"
	Bottom0       = "(b 0)"
	BottomRight10 = "(b r 10)"
	BottomRight20 = "(b r 20)"
	BottomRight30 = "(b r 30)"
	BottomRight40 = "(b r 40)"
	BottomRight50 = "(b r 50)"

	LeftTop30    = "(l t 30)"
	LeftTop20    = "(l t 20)"
	LeftTop10    = "(l t 10)"
	Left0        = "(l 0)"
	LeftBottom10 = "(l b 10)"
	LeftBottom20 = "(l b 20)"
	LeftBottom30 = "(l b 30)"

	RightTop30    = "(r t 30)"
	RightTop20    = "(r t 20)"
	RightTop10    = "(r t 10)"
	Right0        = "(r 0)"
	RightBottom10 = "(r b 10)"
	RightBottom20 = "(r b 20)"
	RightBottom30 = "(r b 30)"
)
